language: go

go:
- 1.12.x
- 1.13.x
- 1.14.x

os: linux

env:
- GO111MODULE=on

script:
- go test ./...
- go test ./cmd/schmp/...
- go build ./cmd/schmp/...

jobs:
  include:
  - stage: deploy
    go: 1.14.x
    deploy:
    - provider: script
      cleanup: false
      script: curl -sL https://git.io/goreleaser | bash
      on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux
