language: go

go:
- 1.12.x
- 1.13.x
- 1.14.x

env:
- GO111MODULE=on

script:
- go test ./...
- go test ./cmd/schmp/...
- go build ./cmd/schmp/...

jobs:
  include:
  - stage: deploy
      go: 1.14.x
      script: curl -sL https://git.io/goreleaser | bash
      deploy:
      - provider: script
        skip_cleanup: true
        on:
          tags: true
          condition: $TRAVIS_OS_NAME = linux
